/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayerPopupBody: typeof import('./components/layer-pop-up/body/LayerPopupBody.vue')['default']
    LayerPopupTitle: typeof import('./components/layer-pop-up/title/LayerPopupTitle.vue')['default']
    MikLayerPopup: typeof import('./components/layer-pop-up/MikLayerPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
